Select T.id, T.FIRST_NAME, T.LAST_NAME, SP.EXPERIENCEYEARS,
CASE WHEN T.PRODUCT_NAME = 'Cell Phone' THEN 'Mobiles' else T.PRODUCT_NAME END AS PRODUCT_NAME,
T.ITEMS_SOLD, T.SOLD_PRICE, T.ITEMS_SOLD*T.SOLD_PRICE AS TOTAL_SALES,
CASE WHEN T.ITEMS_SOLD*T.SOLD_PRICE >= 3000 THEN 'High' when T.ITEMS_SOLD*T.SOLD_PRICE >=15000 THEN 'MEDIUM' ELSE 'LOW' END AS SALES_STATUS,
T.SOLD_DATE, T.COUNTRY, T.REGION
FROM MYDB.ONE_DRIVE.TOTAL_SALE_IN AS T
INNER JOIN
MYDB.POSTGRES_AZURE_SQL_DB_DBO.SALESPERSONS AS SP ON T.ID = SP.SALEPERSONID